kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  # When update to Kubernetes 1.15, make sure to change the
  # apiVersion to "kubeadm.k8s.io/v1beta2".  Also make sure
  # to change the node image in Makefile (--image kindest/node)
  apiVersion: "@KUBEADM_APIVERSION@"
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: "v@KUBERNETES_VERSION@"
  networking:
    serviceSubnet: 10.0.0.0/16
  scheduler:
    extraVolumes:
      - name: "config"
        hostPath: /mnt/host/scheduler
        mountPath: /var/lib/scheduler
        readOnly: true
    extraArgs:
      config: /var/lib/scheduler/scheduler-config.yaml
  controllerManager:
    extraArgs:
      "v": "5"
- |
  apiVersion: "@KUBEADM_APIVERSION@"
  kind: JoinConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      read-only-port: "10255"
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /mnt/host/scheduler
      hostPath: /tmp/topolvm/scheduler
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/controller
      propagation: Bidirectional
# the three workers
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm/lvmd1
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/worker1
      propagation: Bidirectional
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm/lvmd2
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/worker2
      propagation: Bidirectional
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /tmp/topolvm
      hostPath: /tmp/topolvm/lvmd3
    - containerPath: /var/lib/kubelet
      hostPath: /tmp/topolvm/worker3
      propagation: Bidirectional
